"""chat attachments

Revision ID: 0e09f479a6c7
Revises: 7598a28dc508
Create Date: 2026-09-30 01:23:35.887109

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e09f479a6c7"
down_revision: str | Sequence[str] | None = "7598a28dc508"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "attachment_kind",
            sa.Enum(
                "image",
                "video",
                "audio",
                "file",
                name="attachmentkind",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column("messages", sa.Column("attachment_key", sa.String(length=80), nullable=True))
    op.add_column("messages", sa.Column("attachment_name", sa.String(length=255), nullable=True))
    op.add_column(
        "messages", sa.Column("attachment_content_type", sa.String(length=120), nullable=True)
    )
    op.add_column("messages", sa.Column("attachment_size", sa.BigInteger(), nullable=True))
    op.add_column("messages", sa.Column("attachment_duration_ms", sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f("uq_messages_attachment_key"), "messages", ["attachment_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_messages_attachment_key"), "messages", type_="unique")
    op.drop_column("messages", "attachment_duration_ms")
    op.drop_column("messages", "attachment_size")
    op.drop_column("messages", "attachment_content_type")
    op.drop_column("messages", "attachment_name")
    op.drop_column("messages", "attachment_key")
    op.drop_column("messages", "attachment_kind")
    # ### end Alembic commands ###
