"""self registration

Revision ID: 5122ae6ba3e6
Revises: ebf5e146a45d
Create Date: 2026-09-29 11:52:01.978152

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5122ae6ba3e6"
down_revision: str | Sequence[str] | None = "ebf5e146a45d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "pending_approval", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "requested_access_level",
            sa.Enum("member", "manager", "admin", name="accesslevel", native_enum=False, length=20),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("photo_key", sa.String(length=80), nullable=True))
    op.create_index(op.f("ix_users_pending_approval"), "users", ["pending_approval"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_pending_approval"), table_name="users")
    op.drop_column("users", "photo_key")
    op.drop_column("users", "requested_access_level")
    op.drop_column("users", "pending_approval")
    # ### end Alembic commands ###
