"""ai message focus

Revision ID: 529250702263
Revises: 4e0d366c0eb4
Create Date: 2026-09-30 00:59:13.187742

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "529250702263"
down_revision: str | Sequence[str] | None = "4e0d366c0eb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_messages",
        sa.Column(
            "focus_type",
            sa.Enum(
                "project",
                "task",
                "meeting",
                "channel",
                "document",
                "decision",
                name="aifocustype",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column("ai_messages", sa.Column("focus_id", sa.Uuid(), nullable=True))
    op.add_column("ai_messages", sa.Column("focus_title", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_messages", "focus_title")
    op.drop_column("ai_messages", "focus_id")
    op.drop_column("ai_messages", "focus_type")
    # ### end Alembic commands ###
