"""meetings decisions

Revision ID: 6677920bd981
Revises: 07a8b281dee8
Create Date: 2026-09-29 06:38:36.816330

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6677920bd981"
down_revision: str | Sequence[str] | None = "07a8b281dee8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("agenda", sa.Text(), nullable=True),
        sa.Column("minutes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned", "done", "cancelled", name="meetingstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_meetings_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_meetings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
    )
    op.create_index(op.f("ix_meetings_project_id"), "meetings", ["project_id"], unique=False)
    op.create_index(op.f("ix_meetings_scheduled_at"), "meetings", ["scheduled_at"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("meeting_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "validated",
                "rejected",
                name="decisionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("validated_by_id", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resulting_project_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "meeting_id IS NOT NULL OR project_id IS NOT NULL",
            name=op.f("ck_decisions_has_meeting_or_project"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_decisions_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_decisions_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_decisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resulting_project_id"],
            ["projects.id"],
            name=op.f("fk_decisions_resulting_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by_id"],
            ["users.id"],
            name=op.f("fk_decisions_validated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index(op.f("ix_decisions_meeting_id"), "decisions", ["meeting_id"], unique=False)
    op.create_index(op.f("ix_decisions_project_id"), "decisions", ["project_id"], unique=False)
    op.create_index(op.f("ix_decisions_status"), "decisions", ["status"], unique=False)
    op.create_table(
        "meeting_participants",
        sa.Column("meeting_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_meeting_participants_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_meeting_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meeting_id", "user_id", name=op.f("pk_meeting_participants")),
    )
    op.create_index(
        op.f("ix_meeting_participants_user_id"), "meeting_participants", ["user_id"], unique=False
    )
    op.add_column("tasks", sa.Column("meeting_id", sa.Uuid(), nullable=True))
    op.add_column("tasks", sa.Column("decision_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_tasks_decision_id"), "tasks", ["decision_id"], unique=False)
    op.create_index(op.f("ix_tasks_meeting_id"), "tasks", ["meeting_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tasks_decision_id_decisions"),
        "tasks",
        "decisions",
        ["decision_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_tasks_meeting_id_meetings"),
        "tasks",
        "meetings",
        ["meeting_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_meeting_id_meetings"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("fk_tasks_decision_id_decisions"), "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_meeting_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_decision_id"), table_name="tasks")
    op.drop_column("tasks", "decision_id")
    op.drop_column("tasks", "meeting_id")
    op.drop_index(op.f("ix_meeting_participants_user_id"), table_name="meeting_participants")
    op.drop_table("meeting_participants")
    op.drop_index(op.f("ix_decisions_status"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_project_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_meeting_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_meetings_scheduled_at"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_project_id"), table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###
