"""channel photo

Revision ID: c4f5428c0568
Revises: 0e09f479a6c7
Create Date: 2026-09-30 05:26:17.300923

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4f5428c0568"
down_revision: str | Sequence[str] | None = "0e09f479a6c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("photo_key", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "photo_key")
    # ### end Alembic commands ###
